# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IntroWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(461, 420)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.openFPDButton = QtWidgets.QPushButton(self.centralwidget)
        self.openFPDButton.setGeometry(QtCore.QRect(30, 30, 401, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.openFPDButton.setFont(font)
        self.openFPDButton.setObjectName("openFPDButton")
        self.openSIMButton = QtWidgets.QPushButton(self.centralwidget)
        self.openSIMButton.setGeometry(QtCore.QRect(30, 140, 401, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.openSIMButton.setFont(font)
        self.openSIMButton.setObjectName("openSIMButton")
        self.openOPRButton = QtWidgets.QPushButton(self.centralwidget)
        self.openOPRButton.setGeometry(QtCore.QRect(30, 250, 401, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.openOPRButton.setFont(font)
        self.openOPRButton.setObjectName("openOPRButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RoboVac 0.1 - Main Menu"))
        self.openFPDButton.setText(_translate("MainWindow", "Open Floorplan Designer"))
        self.openSIMButton.setText(_translate("MainWindow", "Open Simulator"))
        self.openOPRButton.setText(_translate("MainWindow", "View Previous Runs"))
