# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'opr.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OPRWindow(object):
    def setupUi(self, OPRWindow):
        OPRWindow.setObjectName("OPRWindow")
        OPRWindow.resize(1009, 645)
        self.centralwidget = QtWidgets.QWidget(OPRWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(120, 70, 871, 531))
        self.graphicsView.setObjectName("graphicsView")
        self.openFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.openFileButton.setGeometry(QtCore.QRect(20, 20, 75, 23))
        self.openFileButton.setObjectName("openFileButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(120, 10, 871, 51))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        OPRWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OPRWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1009, 21))
        self.menubar.setObjectName("menubar")
        OPRWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OPRWindow)
        self.statusbar.setObjectName("statusbar")
        OPRWindow.setStatusBar(self.statusbar)

        self.retranslateUi(OPRWindow)
        QtCore.QMetaObject.connectSlotsByName(OPRWindow)

    def retranslateUi(self, OPRWindow):
        _translate = QtCore.QCoreApplication.translate
        OPRWindow.setWindowTitle(_translate("OPRWindow", "MainWindow"))
        self.openFileButton.setText(_translate("OPRWindow", "Open"))
