# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'opr.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OPRWindow(object):
    def setupUi(self, OPRWindow):
        OPRWindow.setObjectName("OPRWindow")
        OPRWindow.resize(494, 110)
        self.centralwidget = QtWidgets.QWidget(OPRWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.openFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.openFileButton.setGeometry(QtCore.QRect(20, 10, 461, 51))
        self.openFileButton.setObjectName("openFileButton")
        OPRWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OPRWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 494, 21))
        self.menubar.setObjectName("menubar")
        OPRWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OPRWindow)
        self.statusbar.setObjectName("statusbar")
        OPRWindow.setStatusBar(self.statusbar)

        self.retranslateUi(OPRWindow)
        QtCore.QMetaObject.connectSlotsByName(OPRWindow)

    def retranslateUi(self, OPRWindow):
        _translate = QtCore.QCoreApplication.translate
        OPRWindow.setWindowTitle(_translate("OPRWindow", "MainWindow"))
        self.openFileButton.setText(_translate("OPRWindow", "Open a Previous Run"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OPRWindow = QtWidgets.QMainWindow()
    ui = Ui_OPRWindow()
    ui.setupUi(OPRWindow)
    OPRWindow.show()
    sys.exit(app.exec_())
