# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Common.ResizableGraphicsView import ResizableGraphicsView


class Ui_PRViewWindow(object):
    def setupUi(self, PRViewWindow):
        PRViewWindow.setObjectName("PRViewWindow")
        PRViewWindow.resize(1166, 600)
        self.centralwidget = QtWidgets.QWidget(PRViewWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.GraphicLayout_2 = QtWidgets.QVBoxLayout()
        self.GraphicLayout_2.setObjectName("GraphicLayout_2")
        self.runView = ResizableGraphicsView(self.centralwidget)
        self.runView.setObjectName("runView")
        self.GraphicLayout_2.addWidget(self.runView)
        self.horizontalLayout.addLayout(self.GraphicLayout_2)
        self.GraphicLayout = QtWidgets.QVBoxLayout()
        self.GraphicLayout.setObjectName("GraphicLayout")
        self.MessageLabel = QtWidgets.QLabel(self.centralwidget)
        self.MessageLabel.setObjectName("MessageLabel")
        self.GraphicLayout.addWidget(self.MessageLabel)
        self.FloorPlanLayout = QtWidgets.QHBoxLayout()
        self.FloorPlanLayout.setObjectName("FloorPlanLayout")
        self.GraphicLayout.addLayout(self.FloorPlanLayout)
        self.pieChartView = ResizableGraphicsView(self.centralwidget)
        self.pieChartView.setObjectName("pieChartView")
        self.GraphicLayout.addWidget(self.pieChartView)
        self.horizontalLayout.addLayout(self.GraphicLayout)
        PRViewWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PRViewWindow)
        self.statusbar.setObjectName("statusbar")
        PRViewWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PRViewWindow)
        QtCore.QMetaObject.connectSlotsByName(PRViewWindow)

    def retranslateUi(self, PRViewWindow):
        _translate = QtCore.QCoreApplication.translate
        PRViewWindow.setWindowTitle(_translate("PRViewWindow", "MainWindow"))
        self.MessageLabel.setText(_translate("PRViewWindow", "Simulation at 2023-11-26 02:26:19.378937\n"
"    Using Algorithm Random Bounce\n"
"    On floorplan C:/Users/Bepis/Documents/GitHub/Robovac/Source/Floor Plans/ResultsTest2.fpd\n"
"    With efficiency 0.75\n"
"    Final duration 00:28:22"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PRViewWindow = QtWidgets.QMainWindow()
    ui = Ui_PRViewWindow()
    ui.setupUi(PRViewWindow)
    PRViewWindow.show()
    sys.exit(app.exec_())
