# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

# import new things from designer to window.py by copying paste

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gv1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.gv1.setGeometry(QtCore.QRect(170, 20, 621, 501))
        self.gv1.setObjectName("gv1")
        self.Button1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button1.setGeometry(QtCore.QRect(40, 30, 75, 23))
        self.Button1.setObjectName("Button1")
        self.Button2 = QtWidgets.QPushButton(self.centralwidget)
        self.Button2.setGeometry(QtCore.QRect(40, 60, 75, 23))
        self.Button2.setObjectName("Button2")
        self.Button3 = QtWidgets.QPushButton(self.centralwidget)
        self.Button3.setGeometry(QtCore.QRect(40, 90, 75, 23))
        self.Button3.setObjectName("Button3")
        self.Button4 = QtWidgets.QPushButton(self.centralwidget)
        self.Button4.setGeometry(QtCore.QRect(40, 120, 75, 23))
        self.Button4.setObjectName("Button4")
        self.Button5 = QtWidgets.QPushButton(self.centralwidget)
        self.Button5.setGeometry(QtCore.QRect(40, 150, 75, 23))
        self.Button5.setObjectName("Button5")
        
        self.Input1 = QtWidgets.QLineEdit(self.centralwidget)
        self.Input1.setGeometry(QtCore.QRect(70, 200, 91, 20))
        self.Input1.setObjectName("Input1")
        self.Input2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Input2.setGeometry(QtCore.QRect(70, 230, 91, 20))
        self.Input2.setObjectName("Input2")
        self.Input3 = QtWidgets.QLineEdit(self.centralwidget)
        self.Input3.setGeometry(QtCore.QRect(70, 260, 91, 20))
        self.Input3.setObjectName("Input3")
        self.Input4 = QtWidgets.QLineEdit(self.centralwidget)
        self.Input4.setGeometry(QtCore.QRect(72, 290, 91, 20))
        self.Input4.setObjectName("Input4")
        self.Input5 = QtWidgets.QLineEdit(self.centralwidget)
        self.Input5.setGeometry(QtCore.QRect(72, 320, 91, 20))
        self.Input5.setObjectName("Input5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 200, 41, 131))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button1.setText(_translate("MainWindow", "1"))
        self.Button2.setText(_translate("MainWindow", "2"))
        self.Button3.setText(_translate("MainWindow", "3"))
        self.Button4.setText(_translate("MainWindow", "4"))
        self.Button5.setText(_translate("MainWindow", "5"))
        self.Input1.setText(_translate("MainWindow", "X"))
        self.Input2.setText(_translate("MainWindow", "Y"))
        self.Input3.setText(_translate("MainWindow", "L"))
        self.Input4.setText(_translate("MainWindow", "H"))
        self.Input5.setText(_translate("MainWindow", "temp"))
        self.label.setText(_translate("MainWindow", "X, Y, L,H"))
