# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (
    QApplication,
    QMainWindow,
    QPushButton,
    QLabel,
    QVBoxLayout,
    QWidget,
    QGraphicsView,
    QGraphicsScene, QGraphicsItem, QSizePolicy
)
import sys
# sys.path.append("/Users/M/Documents/Github/Robovac/Source/Common/")
import json
import os

from Commons.RobotVacuum import Robot

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(878, 745)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalWidget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget_2.sizePolicy().hasHeightForWidth())
        self.verticalWidget_2.setSizePolicy(sizePolicy)
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Button1 = QtWidgets.QPushButton(self.verticalWidget_2)
        self.Button1.setObjectName("Button1")
        self.verticalLayout_6.addWidget(self.Button1)
        self.Button2 = QtWidgets.QPushButton(self.verticalWidget_2)
        self.Button2.setObjectName("Button2")
        self.verticalLayout_6.addWidget(self.Button2)
        self.Button3 = QtWidgets.QPushButton(self.verticalWidget_2)
        self.Button3.setObjectName("Button3")
        self.verticalLayout_6.addWidget(self.Button3)
        self.Button4 = QtWidgets.QPushButton(self.verticalWidget_2)
        self.Button4.setObjectName("Button4")
        self.verticalLayout_6.addWidget(self.Button4)
        self.Button5 = QtWidgets.QPushButton(self.verticalWidget_2)
        self.Button5.setObjectName("Button5")
        self.verticalLayout_6.addWidget(self.Button5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalWidget_2)
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")

        #button 1 generate circle at fixed spot
        self.Input1 = QtWidgets.QLineEdit(self.verticalWidget_2)
        self.Input1.setObjectName("Input1")
        self.Button1.clicked.connect(self.addshape)

        # button 2 generate circle with parameters
        self.verticalLayout_8.addWidget(self.Input1)
        self.Input2 = QtWidgets.QLineEdit(self.verticalWidget_2)
        self.Input2.setObjectName("Input2")
        self.Button2.clicked.connect(self.addwithparameter)

        # button 3 generate a roomba
        self.verticalLayout_8.addWidget(self.Input2)
        self.Input3 = QtWidgets.QLineEdit(self.verticalWidget_2)
        self.Input3.setObjectName("Input3")
        self.verticalLayout_8.addWidget(self.Input3)
        self.Button3.clicked.connect(self.addRobot)



        self.Input4 = QtWidgets.QLineEdit(self.verticalWidget_2)
        self.Input4.setObjectName("Input4")
        self.verticalLayout_8.addWidget(self.Input4)


        self.Input5 = QtWidgets.QLineEdit(self.verticalWidget_2)
        self.Input5.setObjectName("Input5")
        self.verticalLayout_8.addWidget(self.Input5)


        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.verticalWidget_2)
        
        self.scene = QGraphicsScene(self.centralwidget)
        #self.scene = QGraphicsScene()
        self.scene.setSceneRect(0,0,500,500) # makes scene a fixed size 
        # self.setFixedSize(500,500)

        # apparently QGScene() does not hard need central widget, but uncertain about with and without it
        self.ball = self.scene.addEllipse(10,0,20,80)


        self.gv1 = QtWidgets.QGraphicsView(self.scene, self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gv1.sizePolicy().hasHeightForWidth())
        self.gv1.setSizePolicy(sizePolicy)
        self.gv1.setObjectName("gv1")
        self.horizontalLayout.addWidget(self.gv1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 878, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def addshape(self):
        ball = self.scene.addEllipse(20,20,50,50)
        
        # makes item movable by mouse
        ball.setFlag(QGraphicsItem.ItemIsMovable)

    def addwithparameter(self):
        inputx = float(self.Input1.text())
        inputy = float(self.Input2.text())
        inputh = float(self.Input3.text())
        inputl = float(self.Input4.text())
        # has error
        ball2 = self.scene.addEllipse(inputx, inputy, inputl, inputh)
        # generate ball based on input from text box
        ball2.setFlag(QGraphicsItem.ItemIsMovable)

    def addRobot(self):
        robo = Robot()
        
        self.scene.addItem(robo)
        robo.setFlag(QGraphicsItem.ItemIsMovable)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button1.setText(_translate("MainWindow", "1"))
        self.Button2.setText(_translate("MainWindow", "2"))
        self.Button3.setText(_translate("MainWindow", "3"))
        self.Button4.setText(_translate("MainWindow", "4"))
        self.Button5.setText(_translate("MainWindow", "5"))
        self.label.setText(_translate("MainWindow", "X, Y, L,H"))
        self.Input1.setText(_translate("MainWindow", "0"))
        self.Input2.setText(_translate("MainWindow", "0"))
        self.Input3.setText(_translate("MainWindow", "50"))
        self.Input4.setText(_translate("MainWindow", "50"))
        self.Input5.setText(_translate("MainWindow", "temp"))
